# HTML Validation Pre-commit Configuration
# Add this to your .pre-commit-config.yaml file

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-html
      - id: check-yaml
      - id: check-json
      - id: check-xml

  - repo: local
    hooks:
      - id: html-validation-fixer
        name: HTML Validation Fixer
        entry: python fix_html_validation.py --auto-fix
        language: system
        files: \.html$
        pass_filenames: true

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        args: ['--format', 'compact']
        files: \.html$