#!/usr/bin/env tsx

/**
 * Search Index Generator - TypeScript + Lunr.js Implementation
 *
 * This script automatically generates search indices from TypeScript content files
 * using ts-morph for content extraction and Lunr.js for full-text search indexing.
 *
 * Features:
 * - Comprehensive content extraction from all content types (lessons, quizzes, exams, etc.)
 * - Intelligent keyword extraction and enhancement
 * - Lunr.js integration for fast full-text search
 * - Development and production modes
 * - Performance optimization and validation
 *
 * Usage:
 *   Development mode (fast, no validation):
 *     pnpm run generate-search-index:dev
 *     make generate-search-index-dev
 *
 *   Production mode (with validation):
 *     pnpm run generate-search-index:prod
 *     make generate-search-index-prod
 *
 *   Custom arguments:
 *     npx tsx src/scripts/search-indexer.ts --mode=production --verbose
 *
 * Modes:
 *   - development: Fast generation, NLP disabled, no validation (~6s)
 *   - production: Full validation, NLP enabled, TypeScript check (~18s)
 *
 * Generated by: Task 3D - Search Index Generator Implementation
 * Dependencies: ts-morph, lunr, existing type system
 */

import { Project } from "ts-morph";
import lunr from "lunr";
import { writeFileSync } from "fs";
import { join, resolve, relative, basename, dirname } from "path";
import { performance } from "perf_hooks";
import { glob } from "glob";
import type {
	SearchIndexConfig,
	RawContentItem,
	ExtractedCodeBlock,
	ExtractedDiagram,
	ExtractedFlashcard,
	ExtractedQuestion,
	ContentExtractionResult,
	ContentExtractionFailure,
	ExtractionStats,
	LunrIndexResult,
	SearchIndexMetadata,
	IndexGenerationStats,
	SearchableItem,
	SearchNavigationMetadata,
	ChapterType,
	ContentType,
	QuestionType
} from "$types";
import { SETTINGS } from "$config/settings.js";
import { runGeneratedFileValidation } from "$lib/utils/validation-utils.js";

/**
 * Default configuration for search index generation
 * Uses centralized settings from SETTINGS.scripts.searchIndex
 */
const DEFAULT_CONFIG: SearchIndexConfig = {
	contentPath: SETTINGS.scripts.searchIndex.paths.inputFolder,
	outputPath: SETTINGS.scripts.searchIndex.paths.outputFile,
	mode: SETTINGS.scripts.searchIndex.processing.mode,
	enableNLP: SETTINGS.scripts.searchIndex.processing.enableNLP,
	verboseLogging: SETTINGS.scripts.searchIndex.processing.verboseLogging,
	maxKeywords: SETTINGS.scripts.searchIndex.processing.maxKeywords,
	minKeywordLength: SETTINGS.scripts.searchIndex.processing.minKeywordLength,
	fieldBoosts: SETTINGS.scripts.searchIndex.fieldBoosts
};

/**
 * Technical terms dictionary for keyword boosting
 * Uses centralized keywords from SETTINGS.scripts.searchIndex.keywords
 */
function getTechnicalTerms(): string[] {
	const keywords = SETTINGS.scripts.searchIndex.keywords;
	return [
		...keywords.cloudNative,
		...keywords.infrastructure,
		...keywords.languages,
		...keywords.databases,
		...keywords.webTechnologies,
		...keywords.cloudProviders,
		...keywords.security
	];
}

/**
 * Main Search Index Generator Class
 */
class SearchIndexGenerator {
	private config: SearchIndexConfig;
	private project: Project;
	private stats: Partial<IndexGenerationStats> = {};
	private startTime: number = 0;

	constructor(config: Partial<SearchIndexConfig> = {}) {
		this.config = { ...DEFAULT_CONFIG, ...config };
		this.project = new Project({
			tsConfigFilePath: "tsconfig.json",
			skipAddingFilesFromTsConfig: true
		});

		if (this.config.verboseLogging) {
			console.log("🚀 Search Index Generator initialized");
			console.log(`📁 Content path: ${this.config.contentPath}`);
			console.log(`📄 Output path: ${this.config.outputPath}`);
			console.log(`🎯 Mode: ${this.config.mode}`);
			console.log(`🔍 NLP enabled: ${this.config.enableNLP}`);
		}
	}

	/**
	 * Generate the complete search index
	 */
	async generateSearchIndex(_configId?: string): Promise<LunrIndexResult> {
		this.startTime = performance.now();

		try {
			// Step 1: Extract content from TypeScript files
			const extractionStart = performance.now();
			const extractionResult = await this.extractContentFromFiles();
			this.stats.extractionTime = performance.now() - extractionStart;

			if (this.config.verboseLogging) {
				console.log(
					`✅ Extracted ${extractionResult.items.length} items in ${this.stats.extractionTime.toFixed(2)}ms`
				);
			}

			// Step 2: Enrich content with keywords and metadata
			const enrichmentStart = performance.now();
			const enrichedItems = await this.enrichContentItems(extractionResult.items);
			this.stats.enrichmentTime = performance.now() - enrichmentStart;

			// Step 3: Build Lunr.js index
			const indexStart = performance.now();
			const searchableItems = this.convertToSearchableItems(enrichedItems);
			const lunrIndex = this.buildLunrIndex(searchableItems);
			this.stats.indexBuildTime = performance.now() - indexStart;

			// Step 4: Generate metadata
			const metadata = this.generateIndexMetadata(searchableItems, extractionResult.stats);

			// Step 5: Write output file
			const writeStart = performance.now();
			await this.writeIndexFile(lunrIndex, searchableItems, metadata, _configId);
			this.stats.writeTime = performance.now() - writeStart;

			// Final statistics
			this.stats.totalTime = performance.now() - this.startTime;
			this.stats.avgTimePerItem = this.stats.totalTime / searchableItems.length;

			const result: LunrIndexResult = {
				index: lunrIndex.toJSON(),
				items: searchableItems,
				metadata,
				generationStats: this.stats as IndexGenerationStats
			};

			if (this.config.verboseLogging) {
				this.logGenerationStats();
			}

			return result;
		} catch (error) {
			console.error("❌ Search index generation failed:", error);
			throw error;
		}
	}

	/**
	 * Extract content from TypeScript files using ts-morph
	 */
	private async extractContentFromFiles(): Promise<ContentExtractionResult> {
		const pattern = join(this.config.contentPath, "**", "*.ts");
		const files = await glob(pattern);

		if (this.config.verboseLogging) {
			console.log(`📂 Found ${files.length} TypeScript files to process`);
		}

		const items: RawContentItem[] = [];
		const failures: ContentExtractionFailure[] = [];
		const typeDistribution: Record<ChapterType, number> = {
			overview: 0,
			lesson: 0,
			study_guide: 0,
			quiz: 0,
			exam: 0,
			project: 0
		};

		for (const filePath of files) {
			try {
				const rawItem = await this.extractContentFromFile(filePath);
				if (rawItem) {
					items.push(rawItem);
					typeDistribution[rawItem.type]++;

					if (this.config.verboseLogging && items.length % 10 === 0) {
						console.log(`⏳ Processed ${items.length}/${files.length} files...`);
					}
				}
			} catch (error) {
				const failure: ContentExtractionFailure = {
					filePath,
					error: error instanceof Error ? error.message : String(error),
					stackTrace: error instanceof Error ? error.stack : undefined,
					timestamp: new Date()
				};
				failures.push(failure);

				if (this.config.verboseLogging) {
					console.warn(`⚠️  Failed to process ${filePath}: ${failure.error}`);
				}
			}
		}

		// Calculate item counts
		const itemCounts = {
			lessons: typeDistribution.lesson,
			studyGuides: typeDistribution.study_guide,
			quizzes: typeDistribution.quiz,
			exams: typeDistribution.exam,
			projects: typeDistribution.project,
			codeBlocks: items.reduce((sum, item) => sum + item.codeBlocks.length, 0),
			diagrams: items.reduce((sum, item) => sum + item.diagrams.length, 0),
			flashcards: items.reduce((sum, item) => sum + item.flashcards.length, 0),
			questions: items.reduce((sum, item) => sum + item.questions.length, 0)
		};

		const stats: ExtractionStats = {
			totalFiles: files.length,
			successfulFiles: items.length,
			failedFiles: failures.length,
			processingTime: 0, // Will be set by caller
			typeDistribution,
			itemCounts
		};

		return { items, failures, stats };
	}

	/**
	 * Extract content from a single TypeScript file
	 */
	private async extractContentFromFile(filePath: string): Promise<RawContentItem | null> {
		try {
			// Add the source file to the project
			const sourceFile = this.project.addSourceFileAtPath(filePath);

			// Get all exported variables/constants
			const exportedDeclarations = sourceFile.getExportedDeclarations();

			for (const [exportName, _declarations] of exportedDeclarations) {
				// Look for content exports (lessonContent, quizContent, etc.)
				if (this.isContentExport(exportName)) {
					// Use dynamic import to get the actual content
					const contentObject = await this.evaluateContentObject(filePath, exportName);
					if (contentObject && this.isValidContent(contentObject)) {
						return this.processContentObject(filePath, contentObject);
					}
				}
			}

			return null;
		} catch (error) {
			if (this.config.verboseLogging) {
				console.warn(`⚠️  Failed to process file ${filePath}: ${error}`);
			}
			return null;
		}
	}

	/**
	 * Check if export name indicates content
	 */
	private isContentExport(exportName: string): boolean {
		return (
			exportName.includes("Content") ||
			exportName.includes("content") ||
			exportName === "lessonContent" ||
			exportName === "quizContent" ||
			exportName === "examContent" ||
			exportName === "study_guideContent" ||
			exportName === "projectContent"
		);
	}

	/**
	 * Evaluate TypeScript content object safely using dynamic import
	 */
	private async evaluateContentObject(filePath: string, exportName: string): Promise<unknown> {
		try {
			// Use dynamic import to load the module safely
			const resolvedPath = resolve(filePath);
			const module = await import(`file://${resolvedPath}`);
			return module[exportName];
		} catch (error) {
			if (this.config.verboseLogging) {
				console.warn(`⚠️  Failed to import ${exportName} from ${filePath}: ${error}`);
			}
			return null;
		}
	}

	/**
	 * Validate that object is valid content
	 */
	private isValidContent(obj: unknown): obj is Record<string, unknown> {
		return (
			obj !== null && typeof obj === "object" && "type" in obj && "title" in obj && "summary" in obj
		);
	}

	/**
	 * Process content object into RawContentItem
	 */
	private processContentObject(filePath: string, content: Record<string, unknown>): RawContentItem {
		// Extract unit and chapter from file path
		const relativePath = relative(this.config.contentPath, filePath);
		const pathParts = relativePath.split("/");
		const unitId = pathParts[0] || "unknown";
		const filename = basename(filePath, ".ts");
		const chapterMatch = filename.match(/^(\d+)_/);
		const chapterNumber = chapterMatch ? chapterMatch[1] : "00";

		const rawItem: RawContentItem = {
			sourceFile: filePath,
			id: String(content.id || `${unitId}_${filename}`),
			title: String(content.title),
			summary: String(content.summary),
			type: content.type as ChapterType,
			unitId,
			chapterNumber,
			rawContent: content,
			searchableText: this.extractSearchableText(content),
			codeBlocks: this.extractCodeBlocks(content),
			diagrams: this.extractDiagrams(content),
			flashcards: this.extractFlashcards(content),
			questions: this.extractQuestions(content),
			requirements: this.extractRequirements(content),
			manualKeywords: this.extractManualKeywords(content),
			tags: Array.isArray(content.tags) ? content.tags : [],
			difficulty: content.difficulty as RawContentItem["difficulty"],
			technologyUnit: content.technologyUnit as RawContentItem["technologyUnit"],
			estimatedTime: content.estimatedTime as number | undefined,
			prerequisites: Array.isArray(content.prerequisites) ? content.prerequisites : undefined,
			learningObjectives: Array.isArray(content.learningObjectives)
				? content.learningObjectives
				: undefined
		};

		return rawItem;
	}

	/**
	 * Extract searchable text from content sections
	 */
	private extractSearchableText(content: Record<string, unknown>): string {
		let text = "";

		// Add title and summary
		text += `${String(content.title)} ${String(content.summary)} `;

		// Extract from sections (lessons, projects)
		if (content.sections && Array.isArray(content.sections)) {
			for (const section of content.sections) {
				if (section.title) {
					text += `${section.title} `;
				}
				if (section.content && Array.isArray(section.content)) {
					for (const block of section.content) {
						text += this.extractTextFromContentBlock(block);
					}
				}
			}
		}

		// Extract from quiz/exam questions
		const quiz = content.quiz as { questions?: Array<{ question?: string; explanation?: string }> };
		if (quiz?.questions) {
			for (const question of quiz.questions) {
				text += `${String(question.question || "")} `;
				if (question.explanation) {
					text += `${String(question.explanation)} `;
				}
			}
		}

		const exam = content.exam as { questions?: Array<{ question?: string; explanation?: string }> };
		if (exam?.questions) {
			for (const question of exam.questions) {
				text += `${String(question.question || "")} `;
				if (question.explanation) {
					text += `${String(question.explanation)} `;
				}
			}
		}

		// Extract from study guide flashcards
		const studyGuide = content.studyGuide as {
			flashcards?: Array<{ front?: string; back?: string }>;
		};
		if (studyGuide?.flashcards) {
			for (const card of studyGuide.flashcards) {
				text += `${String(card.front || "")} ${String(card.back || "")} `;
			}
		}

		return text.trim();
	}

	/**
	 * Extract text from individual content blocks
	 */
	private extractTextFromContentBlock(block: Record<string, unknown>): string {
		let text = "";

		switch (block.type) {
			case "paragraph":
				if (Array.isArray(block.content)) {
					for (const fragment of block.content) {
						if (fragment.text) {
							text += `${fragment.text} `;
						}
					}
				}
				break;
			case "callout":
				if (block.title) {
					text += `${block.title} `;
				}
				if (Array.isArray(block.content)) {
					for (const fragment of block.content) {
						if (fragment.text) {
							text += `${fragment.text} `;
						}
					}
				}
				break;
			case "code":
				if (block.title) {
					text += `${block.title} `;
				}
				break;
			case "diagram":
				if (block.title) {
					text += `${block.title} `;
				}
				if (block.caption) {
					text += `${block.caption} `;
				}
				break;
		}

		return text;
	}

	/**
	 * Extract code blocks from content
	 */
	private extractCodeBlocks(content: Record<string, unknown>): ExtractedCodeBlock[] {
		const codeBlocks: ExtractedCodeBlock[] = [];

		if (content.sections && Array.isArray(content.sections)) {
			for (const section of content.sections) {
				if (section.content && Array.isArray(section.content)) {
					for (const block of section.content) {
						if (block.type === "code") {
							codeBlocks.push({
								language: block.language || "text",
								code: block.code || "",
								title: block.title,
								filename: block.filename,
								technicalTerms: this.extractTechnicalTerms(block.code || "")
							});
						}
					}
				}
			}
		}

		return codeBlocks;
	}

	/**
	 * Extract diagrams from content
	 */
	private extractDiagrams(content: Record<string, unknown>): ExtractedDiagram[] {
		const diagrams: ExtractedDiagram[] = [];

		if (content.sections && Array.isArray(content.sections)) {
			for (const section of content.sections) {
				if (section.content && Array.isArray(section.content)) {
					for (const block of section.content) {
						if (block.type === "diagram") {
							diagrams.push({
								diagramType: block.diagramType || "mermaid",
								definition: block.definition || "",
								title: block.title,
								caption: block.caption,
								extractedTerms: this.extractTechnicalTerms(
									`${block.title || ""} ${block.caption || ""} ${block.definition || ""}`
								)
							});
						}
					}
				}
			}
		}

		return diagrams;
	}

	/**
	 * Extract flashcards from study guides
	 */
	private extractFlashcards(content: Record<string, unknown>): ExtractedFlashcard[] {
		const flashcards: ExtractedFlashcard[] = [];

		const studyGuide = content.studyGuide as {
			flashcards?: Array<{
				front?: string;
				back?: string;
				tags?: string[];
				category?: string;
				difficulty?: string;
			}>;
		};
		if (studyGuide?.flashcards) {
			for (const card of studyGuide.flashcards) {
				flashcards.push({
					front: String(card.front || ""),
					back: String(card.back || ""),
					tags: card.tags || [],
					category: card.category,
					difficulty: card.difficulty as ExtractedFlashcard["difficulty"]
				});
			}
		}

		return flashcards;
	}

	/**
	 * Extract questions from quizzes and exams
	 */
	private extractQuestions(content: Record<string, unknown>): ExtractedQuestion[] {
		const questions: ExtractedQuestion[] = [];

		// Process quiz questions
		const quiz = content.quiz as { questions?: unknown[] };
		if (quiz?.questions) {
			questions.push(...this.processQuestions(quiz.questions));
		}

		// Process exam questions
		const exam = content.exam as { questions?: unknown[] };
		if (exam?.questions) {
			questions.push(...this.processQuestions(exam.questions));
		}

		return questions;
	}

	/**
	 * Process array of questions
	 */
	private processQuestions(questionsArray: unknown[]): ExtractedQuestion[] {
		return questionsArray.map((q) => {
			const question = q as Record<string, unknown>;
			return {
				type: question.type as QuestionType,
				question: String(question.question || ""),
				options: question.options as string[] | undefined,
				codeSnippet: question.codeSnippet as string | undefined,
				explanation: question.explanation as string | undefined,
				tags: question.tags as string[] | undefined,
				technicalTerms: this.extractTechnicalTerms(
					`${question.question || ""} ${question.explanation || ""} ${question.codeSnippet || ""}`
				)
			};
		});
	}

	/**
	 * Extract project requirements
	 */
	private extractRequirements(content: Record<string, unknown>): string[] {
		if (content.requirements && Array.isArray(content.requirements)) {
			return content.requirements;
		}
		if (content.deliverables && Array.isArray(content.deliverables)) {
			return content.deliverables;
		}
		return [];
	}

	/**
	 * Extract manual keywords from content metadata
	 */
	private extractManualKeywords(content: Record<string, unknown>): string[] {
		const keywords: string[] = [];

		if (content.keywords && Array.isArray(content.keywords)) {
			keywords.push(...content.keywords);
		}

		// Extract from prerequisites and learning objectives
		if (Array.isArray(content.prerequisites)) {
			keywords.push(...content.prerequisites);
		}
		if (Array.isArray(content.learningObjectives)) {
			keywords.push(...content.learningObjectives);
		}

		return keywords;
	}

	/**
	 * Extract technical terms from text
	 */
	private extractTechnicalTerms(text: string): string[] {
		const terms: string[] = [];
		const lowerText = text.toLowerCase();

		for (const term of getTechnicalTerms()) {
			if (lowerText.includes(term.toLowerCase())) {
				terms.push(term);
			}
		}

		return [...new Set(terms)]; // Remove duplicates
	}

	/**
	 * Enrich content items with enhanced keywords
	 */
	private async enrichContentItems(items: RawContentItem[]): Promise<RawContentItem[]> {
		if (this.config.verboseLogging) {
			console.log(`🔍 Enriching ${items.length} content items with keywords...`);
		}

		return items.map((item) => {
			// Combine all extracted technical terms
			const allTechnicalTerms = [
				...item.codeBlocks.flatMap((cb) => cb.technicalTerms),
				...item.diagrams.flatMap((d) => d.extractedTerms),
				...item.questions.flatMap((q) => q.technicalTerms),
				...this.extractTechnicalTerms(item.searchableText)
			];

			// Enhanced keywords combining manual + technical + extracted
			const enhancedKeywords = [
				...item.manualKeywords,
				...allTechnicalTerms,
				...item.tags,
				item.type,
				item.unitId
			].filter((keyword, index, array) => array.indexOf(keyword) === index); // Remove duplicates

			return {
				...item,
				manualKeywords: enhancedKeywords.slice(0, this.config.maxKeywords)
			};
		});
	}

	/**
	 * Convert RawContentItems to SearchableItems
	 */
	private convertToSearchableItems(items: RawContentItem[]): SearchableItem[] {
		return items.map((item) => {
			const searchableItem: SearchableItem = {
				id: item.id,
				title: item.title,
				description: item.summary,
				content: item.searchableText,
				type: this.mapChapterTypeToContentType(item.type),
				category: item.unitId,
				keywords: item.manualKeywords,
				tags: item.tags,
				nav: this.generateNavigationMetadata(item),
				weight: this.calculateItemWeight(item),
				searchMetadata: {
					chapterType: item.type,
					technologyUnit: item.technologyUnit,
					difficulty: item.difficulty,
					estimatedTime: item.estimatedTime,
					prerequisites: item.prerequisites,
					learningObjectives: item.learningObjectives
				}
			};

			return searchableItem;
		});
	}

	/**
	 * Map ChapterType to ContentType
	 */
	private mapChapterTypeToContentType(chapterType: ChapterType): ContentType {
		switch (chapterType) {
			case "lesson":
				return "lesson";
			case "quiz":
			case "exam":
				return "interactive";
			case "study_guide":
				return "text";
			case "project":
				return "mixed";
			case "overview":
				return "text";
			default:
				return "mixed";
		}
	}

	/**
	 * Generate navigation metadata for item
	 */
	private generateNavigationMetadata(item: RawContentItem): SearchNavigationMetadata {
		return {
			unitId: item.unitId,
			chapterId: item.chapterNumber,
			lessonId: item.id,
			path: `#/demo/unit/${item.unitId}/lesson/${item.id}`,
			unitTitle: item.unitId.replace(/unit/, "Unit "),
			chapterNumber: item.chapterNumber,
			breadcrumbPath: ["Home", item.unitId, item.title]
		};
	}

	/**
	 * Calculate search weight for item
	 */
	private calculateItemWeight(item: RawContentItem): number {
		let weight = 1.0;

		// Boost based on content type
		switch (item.type) {
			case "lesson":
				weight += 0.5;
				break;
			case "exam":
				weight += 0.3;
				break;
			case "project":
				weight += 0.4;
				break;
		}

		// Boost based on content richness
		weight += item.codeBlocks.length * 0.1;
		weight += item.diagrams.length * 0.1;
		weight += Math.min(item.manualKeywords.length / 10, 0.3);

		return Math.min(weight, 3.0); // Cap at 3.0
	}

	/**
	 * Build Lunr.js search index
	 */
	private buildLunrIndex(items: SearchableItem[]): lunr.Index {
		if (this.config.verboseLogging) {
			console.log(`🏗️  Building Lunr.js index with ${items.length} items...`);
		}

		return lunr(function () {
			// Configure field boosts
			this.field("title", { boost: 10 });
			this.field("description", { boost: 8 });
			this.field("content", { boost: 5 });
			this.field("keywords", { boost: 9 });
			this.field("tags", { boost: 3 });

			// Set document reference
			this.ref("id");

			// Add documents to index
			items.forEach((item) => {
				this.add({
					id: item.id,
					title: item.title,
					description: item.description,
					content: item.content,
					keywords: item.keywords.join(" "),
					tags: item.tags.join(" ")
				});
			});
		});
	}

	/**
	 * Generate index metadata
	 */
	private generateIndexMetadata(
		items: SearchableItem[],
		_extractionStats: ExtractionStats
	): SearchIndexMetadata {
		const typeDistribution: Record<ContentType, number> = {
			component: 0,
			lesson: 0,
			code: 0,
			diagram: 0,
			interactive: 0,
			text: 0,
			mixed: 0
		};

		const chapterTypeDistribution: Record<ChapterType, number> = {
			overview: 0,
			lesson: 0,
			study_guide: 0,
			quiz: 0,
			exam: 0,
			project: 0
		};

		items.forEach((item) => {
			typeDistribution[item.type]++;
			if (item.searchMetadata?.chapterType) {
				chapterTypeDistribution[item.searchMetadata.chapterType]++;
			}
		});

		return {
			generatedAt: new Date().toISOString(),
			totalItems: items.length,
			typeDistribution,
			chapterTypeDistribution,
			mode: this.config.mode,
			nlpEnabled: this.config.enableNLP,
			version: "1.0.0",
			config: {
				contentPath: this.config.contentPath,
				mode: this.config.mode,
				enableNLP: this.config.enableNLP,
				maxKeywords: this.config.maxKeywords
			}
		};
	}

	/**
	 * Write the generated index to file
	 */
	private async writeIndexFile(
		lunrIndex: lunr.Index,
		items: SearchableItem[],
		metadata: SearchIndexMetadata,
		configId?: string
	): Promise<void> {
		if (this.config.verboseLogging) {
			console.log(`📝 Writing search index to ${this.config.outputPath}...`);
		}

		const indexCode = `// Auto-generated by search-indexer.ts
// Do not edit manually - changes will be overwritten on next build
// Generated: ${metadata.generatedAt}
// Mode: ${metadata.mode} | Items: ${metadata.totalItems} | NLP: ${metadata.nlpEnabled}

import type { SearchableItem, SearchIndexMetadata } from "$types";

/**
 * Search index metadata
 */
export const searchIndexMetadata: SearchIndexMetadata = ${JSON.stringify(metadata, null, 2)};

/**
 * Lunr.js serialized index for client-side search
 */
export const lunrIndexData = ${JSON.stringify(lunrIndex.toJSON(), null, 2)};

/**
 * Searchable content items array
 */
export const searchIndex: SearchableItem[] = ${JSON.stringify(items, null, 2)};

/**
 * Get all searchable content items
 */
export function getSearchableContent(): SearchableItem[] {
	return searchIndex;
}

/**
 * Get search index metadata
 */
export function getSearchIndexMetadata(): SearchIndexMetadata {
	return searchIndexMetadata;
}

/**
 * Basic search function for compatibility
 * For advanced search, use Lunr.js client-side integration
 */
export function searchContent(
	query: string,
	contentType?: string,
	category?: string
): SearchableItem[] {
	if (!query || query.length < 2) {
		return [];
	}

	const searchTerm = query.toLowerCase();
	let results = searchIndex.filter((item) => {
		// Filter by content type
		if (contentType && item.type !== contentType) {
			return false;
		}

		// Filter by category
		if (category && category !== "all" && item.category !== category) {
			return false;
		}

		// Search in title, description, content and keywords
		const searchableText = [
			item.title,
			item.description,
			item.content,
			...item.keywords,
			...item.tags
		]
			.join(" ")
			.toLowerCase();

		return searchableText.includes(searchTerm);
	});

	// Sort by relevance
	results.sort((a, b) => {
		const aTitle = a.title.toLowerCase().includes(searchTerm) ? 3 : 0;
		const aDesc = a.description.toLowerCase().includes(searchTerm) ? 2 : 0;
		const aKeywords = a.keywords.some((k) => k.toLowerCase().includes(searchTerm)) ? 1 : 0;
		const aScore = aTitle + aDesc + aKeywords + a.weight;

		const bTitle = b.title.toLowerCase().includes(searchTerm) ? 3 : 0;
		const bDesc = b.description.toLowerCase().includes(searchTerm) ? 2 : 0;
		const bKeywords = b.keywords.some((k) => k.toLowerCase().includes(searchTerm)) ? 1 : 0;
		const bScore = bTitle + bDesc + bKeywords + b.weight;

		return bScore - aScore;
	});

	return results.slice(0, 50); // Limit results
}
`;

		// Ensure output directory exists
		const outputDir = dirname(this.config.outputPath);
		await this.ensureDirectoryExists(outputDir);

		// Write the file
		writeFileSync(this.config.outputPath, indexCode, "utf8");

		// Run validation if enabled
		if (this.config.mode === "production") {
			await this.validateGeneratedFile(configId);
		}
	}

	/**
	 * Ensure directory exists
	 */
	private async ensureDirectoryExists(dirPath: string): Promise<void> {
		const { mkdirSync, existsSync } = await import("fs");
		if (!existsSync(dirPath)) {
			mkdirSync(dirPath, { recursive: true });
		}
	}

	/**
	 * Validate the generated file
	 * @param configId Optional unique identifier for test isolation
	 */
	private async validateGeneratedFile(configId?: string): Promise<void> {
		try {
			await runGeneratedFileValidation(this.config.outputPath, configId, {
				includeFormat: true,
				includeLint: true,
				includeCheck: true,
				enabled: true
			});
		} catch (error) {
			console.warn("⚠️  Generated file validation failed:", error);
		}
	}

	/**
	 * Log generation statistics
	 */
	private logGenerationStats(): void {
		console.log("\n📊 Search Index Generation Complete!");
		console.log("=====================================");
		console.log(`⏱️  Total time: ${this.stats.totalTime?.toFixed(2)}ms`);
		console.log(`📄 Output file: ${this.config.outputPath}`);
		console.log(`📈 Performance breakdown:`);
		console.log(`   • Extraction: ${this.stats.extractionTime?.toFixed(2)}ms`);
		console.log(`   • Enrichment: ${this.stats.enrichmentTime?.toFixed(2)}ms`);
		console.log(`   • Index build: ${this.stats.indexBuildTime?.toFixed(2)}ms`);
		console.log(`   • File write: ${this.stats.writeTime?.toFixed(2)}ms`);
		console.log(`⚡ Avg per item: ${this.stats.avgTimePerItem?.toFixed(2)}ms`);
		console.log("✅ Generation successful!\n");
	}
}

/**
 * CLI argument parsing
 */
function parseArguments(): Partial<SearchIndexConfig> {
	const args = process.argv.slice(2);
	const config: Partial<SearchIndexConfig> = {};

	for (const arg of args) {
		if (arg.startsWith("--mode=")) {
			const mode = arg.split("=")[1] as "development" | "production";
			config.mode = mode;
			config.enableNLP = mode === "production";
		} else if (arg === "--verbose") {
			config.verboseLogging = true;
		} else if (arg === "--no-nlp") {
			config.enableNLP = false;
		} else if (arg.startsWith("--output=")) {
			config.outputPath = arg.split("=")[1];
		}
	}

	return config;
}

/**
 * Main execution
 */
async function main(): Promise<void> {
	try {
		console.log("🔄 Starting Search Index Generation...\n");

		const config = parseArguments();
		const generator = new SearchIndexGenerator(config);
		const result = await generator.generateSearchIndex();

		console.log(`🎉 Successfully generated search index with ${result.items.length} items!`);
		console.log(`📁 File: ${config.outputPath || DEFAULT_CONFIG.outputPath}`);

		process.exit(0);
	} catch (error) {
		console.error("\n❌ Search index generation failed:");
		console.error(error);
		process.exit(1);
	}
}

// Execute if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
	main();
}

export { SearchIndexGenerator };
