/**
 * ValidationService Test Suite
 *
 * Tests the generic ValidationService that uses Zod schemas for runtime validation.
 * Uses TemplateGenerator to create realistic content for validation testing.
 */

import { describe, it, expect, beforeEach } from "vitest";
import { ValidationService } from "$lib/services/ValidationService.js";
import {
	generateLessonContent,
	generateQuizContent,
	generateStudyGuideContent,
	generateExamContent,
	generateProjectContent
} from "$lib/utils/template-generator.js";
import type { ValidatedScaffoldingArgs, ChapterType } from "$types";

// Helper to create test args
const createTestArgs = (
	type: ChapterType,
	unit: string = "1",
	id: string = "01_01"
): ValidatedScaffoldingArgs => ({
	unit: {
		type: "string" as const,
		value: unit
	},
	type,
	id
});

describe("ValidationService", () => {
	let service: ValidationService;

	beforeEach(() => {
		service = new ValidationService();
	});

	describe("validate() - Valid Content from TemplateGenerator", () => {
		it("DEBUG: show validation errors for template-generated lesson", async () => {
			const args = createTestArgs("lesson");
			const content = generateLessonContent(args);

			console.log("\n=== GENERATED CONTENT STRUCTURE ===");
			console.log("Keys:", Object.keys(content));
			console.log("Type:", content.type);
			console.log("Has ID:", "id" in content);
			console.log("Has metadata:", "metadata" in content);
			console.log("Sections count:", content.sections?.length);

			const result = await service.validate(content);

			console.log("\n=== VALIDATION RESULT ===");
			console.log("Success:", result.success);
			console.log("Errors:", JSON.stringify(result.errors, null, 2));

			expect(result).toBeDefined();
		});

		it("should accept valid LessonContent generated by TemplateGenerator", async () => {
			const args = createTestArgs("lesson");
			const content = generateLessonContent(args);

			const result = await service.validate(content);

			expect(result.success).toBe(true);
			expect(result.errors).toHaveLength(0);
			expect(result.validatedData).toBeDefined();
			expect(result.validatedData).toHaveProperty("type", "lesson");
		});

		it("should accept valid QuizContent generated by TemplateGenerator", async () => {
			const args = createTestArgs("quiz");
			const content = generateQuizContent(args);

			const result = await service.validate(content);
			console.log("Quiz validation errors:", JSON.stringify(result.errors, null, 2));

			expect(result.success).toBe(true);
			expect(result.errors).toHaveLength(0);
			expect(result.validatedData).toBeDefined();
			expect(result.validatedData).toHaveProperty("type", "quiz");
		});

		it("should accept valid StudyGuideContent generated by TemplateGenerator", async () => {
			const args = createTestArgs("study_guide");
			const content = generateStudyGuideContent(args);

			const result = await service.validate(content);

			console.log("StudyGuide validation errors:", JSON.stringify(result.errors, null, 2));
			expect(result.success).toBe(true);
			expect(result.errors).toHaveLength(0);
			expect(result.validatedData).toBeDefined();
			expect(result.validatedData).toHaveProperty("type", "study_guide");
		});

		it("should accept valid ExamContent generated by TemplateGenerator", async () => {
			const args = createTestArgs("exam");
			const content = generateExamContent(args);

			const result = await service.validate(content);

			expect(result.success).toBe(true);
			console.log("Exam validation errors:", JSON.stringify(result.errors, null, 2));
			expect(result.errors).toHaveLength(0);
			expect(result.validatedData).toBeDefined();
			expect(result.validatedData).toHaveProperty("type", "exam");
		});

		it("should accept valid ProjectContent generated by TemplateGenerator", async () => {
			const args = createTestArgs("project");
			const content = generateProjectContent(args);

			const result = await service.validate(content);

			expect(result.success).toBe(true);
			expect(result.errors).toHaveLength(0);
			expect(result.validatedData).toBeDefined();
			expect(result.validatedData).toHaveProperty("type", "project");
		});
	});

	describe("validate() - Invalid Structure", () => {
		it("should reject content with missing required fields", async () => {
			const invalid = {
				type: "lesson"
				// Missing id, title, summary, sections, metadata
			};

			const result = await service.validate(invalid);

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
			expect(result.errors.some((err) => err.toLowerCase().includes("id"))).toBe(true);
		});

		it("should reject content with invalid type", async () => {
			const invalid = {
				type: "invalid_type",
				id: "test",
				title: "Test",
				summary: "Test summary with enough characters"
			};

			const result = await service.validate(invalid);

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});

		it("should reject content with invalid field types", async () => {
			const invalid = {
				type: "lesson",
				id: 123, // Should be string
				title: "Test",
				summary: "Test"
			};

			const result = await service.validate(invalid);

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});
	});

	describe("validate() - Business Rule Violations", () => {
		it("should reject LessonContent with fewer than 5 sections", async () => {
			const args = createTestArgs("lesson");
			const validContent = generateLessonContent(args);

			// Truncate sections to violate minimum rule
			const invalidContent = {
				...validContent,
				sections: validContent.sections.slice(0, 2) // Only 2 sections, minimum is 5
			};

			const result = await service.validate(invalidContent);

			expect(result.success).toBe(false);
			expect(result.errors.some((err) => err.toLowerCase().includes("section"))).toBe(true);
		});

		it("should reject QuizContent with fewer than 10 questions", async () => {
			const args = createTestArgs("quiz");
			const validContent = generateQuizContent(args);

			// Truncate questions to violate minimum rule
			const invalidContent = {
				...validContent,
				quiz: {
					...validContent.quiz,
					questions: validContent.quiz.questions.slice(0, 5) // Only 5 questions, minimum is 10
				}
			};

			const result = await service.validate(invalidContent);

			expect(result.success).toBe(false);
			expect(result.errors.some((err) => err.toLowerCase().includes("question"))).toBe(true);
		});

		it("should reject StudyGuideContent with fewer than 6 flip cards", async () => {
			const args = createTestArgs("study_guide");
			const validContent = generateStudyGuideContent(args);

			// Truncate flip cards to violate minimum rule
			// Truncate flip cards to violate minimum rule
			const invalidContent = {
				...validContent,
				flipCards: validContent.flipCards.slice(0, 3) // Only 3 cards, minimum is 6
			};

			const result = await service.validate(invalidContent);

			expect(result.success).toBe(false);
			expect(result.errors.some((err) => err.toLowerCase().includes("card"))).toBe(true);
		});
	});

	describe("validate() - Mermaid Diagram Validation", () => {
		it("should validate content without Mermaid diagrams successfully", async () => {
			const args = createTestArgs("quiz");
			const content = generateQuizContent(args); // Quizzes don't have diagrams

			const result = await service.validate(content);

			expect(result.success).toBe(true);
			expect(result.errors).toHaveLength(0);
		});

		it("should process content with valid Mermaid diagrams", async () => {
			const args = createTestArgs("lesson");
			const content = generateLessonContent(args); // Lessons include diagrams

			const result = await service.validate(content);

			// TemplateGenerator should create valid diagrams
			expect(result.success).toBe(true);
			expect(result.errors).toHaveLength(0);
		});
	});

	describe("validate() - Edge Cases", () => {
		it("should handle null content gracefully", async () => {
			const result = await service.validate(null);

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});

		it("should handle undefined content gracefully", async () => {
			const result = await service.validate(undefined);

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});

		it("should handle empty object gracefully", async () => {
			const result = await service.validate({});

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});

		it("should handle array input gracefully", async () => {
			const result = await service.validate([]);

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});

		it("should handle string input gracefully", async () => {
			const result = await service.validate("not an object");

			expect(result.success).toBe(false);
			expect(result.errors.length).toBeGreaterThan(0);
		});
	});

	describe("Configuration Management", () => {
		it("should allow updating configuration", () => {
			const newConfig = { enableMermaidValidation: false };
			service.updateConfig(newConfig);

			const config = service.getConfig();
			expect(config.enableMermaidValidation).toBe(false);
		});

		it("should return current configuration", () => {
			const config = service.getConfig();

			expect(config).toHaveProperty("enableMermaidValidation");
			expect(config).toHaveProperty("enableBusinessRules");
			expect(config).toHaveProperty("enableTypeValidation");
		});

		it("should skip Mermaid validation when disabled", async () => {
			service.updateConfig({ enableMermaidValidation: false });

			const args = createTestArgs("lesson");
			const content = generateLessonContent(args);

			// Modify content to have invalid Mermaid syntax
			const contentWithInvalidDiagram = {
				...content,
				sections: content.sections.map((section, idx) => {
					if (idx === 0) {
						return {
							...section,
							content: section.content.map((block) => {
								if (block.type === "diagram") {
									return {
										...block,
										definition: "INVALID MERMAID SYNTAX !!!"
									};
								}
								return block;
							})
						};
					}
					return section;
				})
			};

			const result = await service.validate(contentWithInvalidDiagram);

			// Should pass because Mermaid validation is disabled
			// (Zod structure validation still passes)
			expect(result.success).toBe(true);
		});
	});

	describe("Integration - TemplateGenerator Output Validation", () => {
		it("should validate that all TemplateGenerator outputs pass validation", async () => {
			const types: ChapterType[] = ["lesson", "quiz", "study_guide", "exam", "project"];
			const generators = [
				generateLessonContent,
				generateQuizContent,
				generateStudyGuideContent,
				generateExamContent,
				generateProjectContent
			];

			for (let i = 0; i < types.length; i++) {
				const args = createTestArgs(types[i]);
				const content = generators[i](args);
				const result = await service.validate(content);

				expect(result.success).toBe(true);
				expect(result.errors).toHaveLength(0);
			}
		});

		it("should validate content generated with different unit numbers", async () => {
			const units = ["1", "2", "3", "10", "99"];

			for (const unit of units) {
				const args = createTestArgs("lesson", unit);
				const content = generateLessonContent(args);
				const result = await service.validate(content);

				expect(result.success).toBe(true);
				expect(result.errors).toHaveLength(0);
			}
		});
	});
});
