on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  lint-html-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run HTMLProofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: './' # Check the entire repository
          allow_hash_href: true # Allows href="#" anchors
          disable_external: false # Checks external links
          check_html: true # Enable HTML validation
          # The original action had check_external_hash: true, which is covered by disable_external: false
          # The original action had log_level: 'info', which is not directly supported by athackst/htmlproofer-action
          ignore_urls: '/^http:\/\/localhost/,/^http:\/\/127.0.0.1/'

  lint-mermaid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable LTS version

      - name: Install Dependencies
        run: npm install

      - name: Run Mermaid Validation Script
        run: node src/js/validate-mermaid.js